BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS eng_voc (
	engID	INTEGER NOT NULL PRIMARY KEY UNIQUE,
	word	TEXT NOT NULL,
	category	TEXT NOT NULL
);
INSERT INTO eng_voc VALUES (1,'January','months');
INSERT INTO eng_voc VALUES (2,'February','months');
INSERT INTO eng_voc VALUES (3,'March','months');
INSERT INTO eng_voc VALUES (4,'April','months');
INSERT INTO eng_voc VALUES (5,'May','months');
INSERT INTO eng_voc VALUES (6,'June','months');
INSERT INTO eng_voc VALUES (7,'July','months');
INSERT INTO eng_voc VALUES (8,'August','months');
INSERT INTO eng_voc VALUES (9,'September','months');
INSERT INTO eng_voc VALUES (10,'October','months');
INSERT INTO eng_voc VALUES (11,'November','months');
INSERT INTO eng_voc VALUES (12,'December','months');
INSERT INTO eng_voc VALUES (13,'Monday','weekdays');
INSERT INTO eng_voc VALUES (14,'Tuesday','weekdays');
INSERT INTO eng_voc VALUES (15,'Wednesday','weekdays');
INSERT INTO eng_voc VALUES (16,'Thursday','weekdays');
INSERT INTO eng_voc VALUES (17,'Friday','weekdays');
INSERT INTO eng_voc VALUES (18,'Saturday','weekdays');
INSERT INTO eng_voc VALUES (19,'Sunday','weekdays');
INSERT INTO eng_voc VALUES (20,'red','colors');
INSERT INTO eng_voc VALUES (21,'green','colors');
INSERT INTO eng_voc VALUES (22,'blue','colors');
INSERT INTO eng_voc VALUES (23,'yellow','colors');
INSERT INTO eng_voc VALUES (24,'black','colors');
INSERT INTO eng_voc VALUES (25,'white','colors');
INSERT INTO eng_voc VALUES (26,'orange','colors');
INSERT INTO eng_voc VALUES (27,'purple','colors');
INSERT INTO eng_voc VALUES (28,'pink','colors');
INSERT INTO eng_voc VALUES (29,'brown','colors');
INSERT INTO eng_voc VALUES (30,'mother','family');
INSERT INTO eng_voc VALUES (31,'father','family');
INSERT INTO eng_voc VALUES (32,'sister','family');
INSERT INTO eng_voc VALUES (33,'brother','family');
INSERT INTO eng_voc VALUES (34,'wife','family');
INSERT INTO eng_voc VALUES (35,'husband','family');
INSERT INTO eng_voc VALUES (36,'son','family');
INSERT INTO eng_voc VALUES (37,'daughter','family');
INSERT INTO eng_voc VALUES (38,'sunny','weather');
INSERT INTO eng_voc VALUES (39,'windy','weather');
INSERT INTO eng_voc VALUES (40,'rainy','weather');
INSERT INTO eng_voc VALUES (41,'snowy','weather');
INSERT INTO eng_voc VALUES (42,'cloudy','weather');
INSERT INTO eng_voc VALUES (43,'left','directions');
INSERT INTO eng_voc VALUES (44,'right','directions');
INSERT INTO eng_voc VALUES (45,'straight','directions');
INSERT INTO eng_voc VALUES (46,'back','directions');
INSERT INTO eng_voc VALUES (47,'Hello','greetings');
INSERT INTO eng_voc VALUES (48,'Welcome','greetings');
INSERT INTO eng_voc VALUES (49,'Goodbye','greetings');
INSERT INTO eng_voc VALUES (50,'Nice to meet you','greetings');
INSERT INTO eng_voc VALUES (51,'Thank you','greetings');
INSERT INTO eng_voc VALUES (52,'You''re welcome','greetings');
INSERT INTO eng_voc VALUES (53,'Good morning','greetings');
INSERT INTO eng_voc VALUES (54,'Good evening','greetings');
INSERT INTO eng_voc VALUES (55,'Good night','greetings');
INSERT INTO eng_voc VALUES (56,'kitchen','home');
INSERT INTO eng_voc VALUES (57,'living room','home');
INSERT INTO eng_voc VALUES (58,'bedroom','home');
INSERT INTO eng_voc VALUES (59,'bathroom','home');
INSERT INTO eng_voc VALUES (60,'hallway','home');
INSERT INTO eng_voc VALUES (61,'backyard','home');
INSERT INTO eng_voc VALUES (62,'balcony','home');
INSERT INTO eng_voc VALUES (63,'car','vehicles');
INSERT INTO eng_voc VALUES (64,'bus','vehicles');
INSERT INTO eng_voc VALUES (65,'train','vehicles');
INSERT INTO eng_voc VALUES (66,'bike','vehicles');
INSERT INTO eng_voc VALUES (67,'airplane','vehicles');
INSERT INTO eng_voc VALUES (68,'scooter','vehicles');
INSERT INTO eng_voc VALUES (69,'motorcycle','vehicles');
INSERT INTO eng_voc VALUES (70,'pants','clothes');
INSERT INTO eng_voc VALUES (71,'shoes','clothes');
INSERT INTO eng_voc VALUES (72,'glasses','clothes');
INSERT INTO eng_voc VALUES (73,'hat','clothes');
INSERT INTO eng_voc VALUES (74,'sweater','clothes');
INSERT INTO eng_voc VALUES (75,'shirt','clothes');
INSERT INTO eng_voc VALUES (76,'skirt','clothes');
INSERT INTO eng_voc VALUES (77,'dress','clothes');
INSERT INTO eng_voc VALUES (78,'jacket','clothes');
INSERT INTO eng_voc VALUES (79,'hospital','buildings');
INSERT INTO eng_voc VALUES (80,'police station','buildings');
INSERT INTO eng_voc VALUES (81,'main station','buildings');
INSERT INTO eng_voc VALUES (82,'airport','buildings');
INSERT INTO eng_voc VALUES (83,'firehouse','buildings');
INSERT INTO eng_voc VALUES (84,'school','buildings');
INSERT INTO eng_voc VALUES (85,'city hall','buildings');
INSERT INTO eng_voc VALUES (86,'doctor','occupation');
INSERT INTO eng_voc VALUES (87,'teacher','occupation');
INSERT INTO eng_voc VALUES (88,'engineer','occupation');
INSERT INTO eng_voc VALUES (89,'student','occupation');
INSERT INTO eng_voc VALUES (90,'chef','occupation');
INSERT INTO eng_voc VALUES (91,'lawyer','occupation');
INSERT INTO eng_voc VALUES (92,'nurse','occupation');
INSERT INTO eng_voc VALUES (93,'door','parts-of-building');
INSERT INTO eng_voc VALUES (94,'window','parts-of-building');
INSERT INTO eng_voc VALUES (95,'wall','parts-of-building');
INSERT INTO eng_voc VALUES (96,'ceiling','parts-of-building');
INSERT INTO eng_voc VALUES (97,'floor','parts-of-building');
INSERT INTO eng_voc VALUES (98,'roof','parts-of-building');
INSERT INTO eng_voc VALUES (99,'pencil','education');
INSERT INTO eng_voc VALUES (100,'ruler','education');
INSERT INTO eng_voc VALUES (101,'notebook','education');
INSERT INTO eng_voc VALUES (102,'pen','education');
INSERT INTO eng_voc VALUES (103,'eraser','education');
INSERT INTO eng_voc VALUES (104,'bread','food');
INSERT INTO eng_voc VALUES (105,'apple','food');
INSERT INTO eng_voc VALUES (106,'milk','food');
INSERT INTO eng_voc VALUES (107,'banana','food');
INSERT INTO eng_voc VALUES (108,'water','food');
INSERT INTO eng_voc VALUES (109,'coffee','food');
INSERT INTO eng_voc VALUES (110,'rice','food');
INSERT INTO eng_voc VALUES (111,'tea','food');
INSERT INTO eng_voc VALUES (112,'cheese','food');
INSERT INTO eng_voc VALUES (113,'sausage','food');
INSERT INTO eng_voc VALUES (114,'cookie','food');
INSERT INTO eng_voc VALUES (115,'noodles','food');
INSERT INTO eng_voc VALUES (116,'egg','food');
INSERT INTO eng_voc VALUES (117,'potato','food');
INSERT INTO eng_voc VALUES (118,'cat','animal');
INSERT INTO eng_voc VALUES (119,'dog','animal');
INSERT INTO eng_voc VALUES (120,'mouse','animal');
INSERT INTO eng_voc VALUES (121,'bird','animal');
INSERT INTO eng_voc VALUES (122,'monkey','animal');
INSERT INTO eng_voc VALUES (123,'head','body parts');
INSERT INTO eng_voc VALUES (124,'arm','body parts');
INSERT INTO eng_voc VALUES (125,'hand','body parts');
INSERT INTO eng_voc VALUES (126,'leg','body parts');
INSERT INTO eng_voc VALUES (127,'foot','body parts');
INSERT INTO eng_voc VALUES (128,'eyes','body parts');
INSERT INTO eng_voc VALUES (129,'nose','body parts');
INSERT INTO eng_voc VALUES (130,'mouth','body parts');
INSERT INTO eng_voc VALUES (131,'ears','body parts');
INSERT INTO eng_voc VALUES (132,'hair','body parts');
INSERT INTO eng_voc VALUES (133,'table','furniture');
INSERT INTO eng_voc VALUES (134,'chair','furniture');
INSERT INTO eng_voc VALUES (135,'bed','furniture');
INSERT INTO eng_voc VALUES (136,'bookshelf','furniture');
INSERT INTO eng_voc VALUES (137,'refrigerator','furniture');
INSERT INTO eng_voc VALUES (138,'TV','furniture');
INSERT INTO eng_voc VALUES (139,'wardrobe','furniture');
INSERT INTO eng_voc VALUES (140,'sofa','furniture');
INSERT INTO eng_voc VALUES (141,'fuck you','swear words');
INSERT INTO eng_voc VALUES (142,'shit','swear words');
INSERT INTO eng_voc VALUES (143,'bitch','swear words');
INSERT INTO eng_voc VALUES (144,'asshole','swear words');
INSERT INTO eng_voc VALUES (145,'dumbass','swear words');
INSERT INTO eng_voc VALUES (146,'1','numbers');
INSERT INTO eng_voc VALUES (147,'2','numbers');
INSERT INTO eng_voc VALUES (148,'3','numbers');
INSERT INTO eng_voc VALUES (149,'4','numbers');
INSERT INTO eng_voc VALUES (150,'5','numbers');
INSERT INTO eng_voc VALUES (151,'6','numbers');
INSERT INTO eng_voc VALUES (152,'7','numbers');
INSERT INTO eng_voc VALUES (153,'8','numbers');
INSERT INTO eng_voc VALUES (154,'9','numbers');
INSERT INTO eng_voc VALUES (155,'10','numbers');
INSERT INTO eng_voc VALUES (156,'11','numbers');
INSERT INTO eng_voc VALUES (157,'12','numbers');
INSERT INTO eng_voc VALUES (158,'13','numbers');
INSERT INTO eng_voc VALUES (159,'14','numbers');
INSERT INTO eng_voc VALUES (160,'15','numbers');
INSERT INTO eng_voc VALUES (161,'16','numbers');
INSERT INTO eng_voc VALUES (162,'17','numbers');
INSERT INTO eng_voc VALUES (163,'18','numbers');
INSERT INTO eng_voc VALUES (164,'19','numbers');
INSERT INTO eng_voc VALUES (165,'20','numbers');
INSERT INTO eng_voc VALUES (166,'21','numbers');
INSERT INTO eng_voc VALUES (167,'22','numbers');
INSERT INTO eng_voc VALUES (168,'23','numbers');
INSERT INTO eng_voc VALUES (169,'24','numbers');
INSERT INTO eng_voc VALUES (170,'25','numbers');
INSERT INTO eng_voc VALUES (171,'26','numbers');
INSERT INTO eng_voc VALUES (172,'27','numbers');
INSERT INTO eng_voc VALUES (173,'28','numbers');
INSERT INTO eng_voc VALUES (174,'29','numbers');
INSERT INTO eng_voc VALUES (175,'30','numbers');
INSERT INTO eng_voc VALUES (176,'40','numbers');
INSERT INTO eng_voc VALUES (177,'50','numbers');
INSERT INTO eng_voc VALUES (178,'60','numbers');
INSERT INTO eng_voc VALUES (179,'70','numbers');
INSERT INTO eng_voc VALUES (180,'80','numbers');
INSERT INTO eng_voc VALUES (181,'90','numbers');
INSERT INTO eng_voc VALUES (182,'100','numbers');
INSERT INTO eng_voc VALUES (183,'110','numbers');
INSERT INTO eng_voc VALUES (184,'120','numbers');
INSERT INTO eng_voc VALUES (185,'130','numbers');
INSERT INTO eng_voc VALUES (186,'200','numbers');
INSERT INTO eng_voc VALUES (187,'300','numbers');
INSERT INTO eng_voc VALUES (188,'1000','numbers');
COMMIT;
